apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: "{{.Values.image.repository}}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
