apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - port: 80       # The port that will be exposed inside the cluster
      targetPort: 8080    # The port your Spring Boot application is listening on
      nodePort: 30036     # The port on each node to expose the service (range: 30000-32767)
      protocol: TCP
